#!/usr/bin/env python3
"""Embeds the base conf resource and the pre-formatted FAT16 disk heads (zstd)
into a generated header, compiled into BOTH builds so the driver composes
identical configuration everywhere.

Only dosbox-x.base.conf is embedded. The machine-year .conf files beside it are
no longer part of the core: the ten machines are declared as PRESETS in
waterbox.config, the frontend resolves a preset into settings before the core
sees anything, and the .conf files stay in conf/ as the authored reference that
tools/check-preset-machines.py holds those presets to.

It also embeds the Use Chimera Mouse Driver disk, built by
guest-tools/make-floppy.py: only its head, since the rest of a floppy that
holds 200 KB is zeros the memory file supplies by itself.

usage: gen-assets.py <output.h> <conf-dir> <hdd-dir> <font-dir> <guest-tools-dir>
"""
import importlib.util
import os
import sys

out, confdir, hdddir, fontdir, toolsdir = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5]

def carray(name, data):
    lines = [f'static const unsigned char {name}[] = {{']
    for i in range(0, len(data), 16):
        lines.append('\t' + ' '.join(f'0x{b:02x},' for b in data[i:i + 16]))
    lines.append('};')
    return '\n'.join(lines)

chunks = ['/* generated by gen-assets.py - do not edit */', '#pragma once', '#include <stddef.h>', '']
base = open(os.path.join(confdir, 'dosbox-x.base.conf'), 'rb').read()
chunks.append(carray('conf_base', base))
chunks.append('#define dosdrv_conf_base conf_base')
chunks.append('#define dosdrv_conf_base_len (sizeof conf_base)')
chunks.append('')

# the disk heads: name -> (zst bytes, full image size). The enum sizes are the
# BizHawk HardDiskOptions values; the zst holds only the nonzero head and the
# memory file's grow supplies the zero tail.
SIZES = {'21mb': 21411840, '41mb': 42823680, '241mb': 252370944,
         '504mb': 527966208, '2014mb': 2111864832}
disks = []
for fn in sorted(os.listdir(hdddir)):
    if not fn.endswith('.img.zst'):
        continue
    key = fn.split('.fat16.')[1][:-len('.img.zst')]
    data = open(os.path.join(hdddir, fn), 'rb').read()
    ident = 'hdd_' + key
    chunks.append(carray(ident, data))
    disks.append((key, ident, SIZES[key]))

chunks.append('static const struct { const char *name; const unsigned char *zst; size_t zstLen; unsigned long long imageSize; } dosdrv_formatted_disks[] = {')
for key, ident, size in disks:
    chunks.append(f'\t{{ "{key}", {ident}, sizeof {ident}, {size}ULL }},')
chunks.append('};')
chunks.append('')

# the free fonts DOSBox-X ships beside its executable and looks for by name
# (contrib/fonts): the PC-98 character set, and Unifont as FONTX2 for DOS/V and
# JEGA. A desktop install has them on disk; the sandbox has no disk, so they
# travel in the binary and the driver writes them where they are looked for.
FONTS = ['FREECG98.BMP', 'UnifontExMonoAnk.fontx2', 'UnifontExMonoKanji.fontx2']
for fn in FONTS:
    chunks.append(carray('font_' + fn.replace('.', '_'), open(os.path.join(fontdir, fn), 'rb').read()))
chunks.append('static const struct { const char *name; const unsigned char *data; size_t len; } dosdrv_fonts[] = {')
for fn in FONTS:
    ident = 'font_' + fn.replace('.', '_')
    chunks.append(f'\t{{ "{fn}", {ident}, sizeof {ident} }},')
chunks.append('};')
chunks.append('')

# the mouse driver disk (chimera#135)
spec = importlib.util.spec_from_file_location('make_floppy', os.path.join(toolsdir, 'make-floppy.py'))
floppy = importlib.util.module_from_spec(spec)
spec.loader.exec_module(floppy)
image = floppy.build()
head = image.rstrip(b'\0')
head += b'\0' * (-len(head) % 512)
chunks.append(carray('mouse_disk_head', head))
chunks.append(f'#define dosdrv_mouse_disk_head mouse_disk_head')
chunks.append(f'#define dosdrv_mouse_disk_size {len(image)}u')
chunks.append('')

open(out, 'w').write('\n'.join(chunks))
print(f'{out}: base conf ({len(base)} bytes), {len(disks)} disks')
