#!/usr/bin/env python3
"""Embeds the conf resources (base + machine-year presets) and the
pre-formatted FAT16 disk heads (zstd) into a generated header, compiled into
BOTH builds so the driver composes identical configuration everywhere.

usage: gen-assets.py <output.h> <conf-dir> <hdd-dir>
"""
import os
import sys

out, confdir, hdddir = sys.argv[1], sys.argv[2], sys.argv[3]

def carray(name, data):
    lines = [f'static const unsigned char {name}[] = {{']
    for i in range(0, len(data), 16):
        lines.append('\t' + ' '.join(f'0x{b:02x},' for b in data[i:i + 16]))
    lines.append('};')
    return '\n'.join(lines)

chunks = ['/* generated by gen-assets.py - do not edit */', '#pragma once', '#include <stddef.h>', '']
presets = []
for fn in sorted(os.listdir(confdir)):
    if not fn.endswith('.conf') or 'osconfig' in fn:
        continue
    data = open(os.path.join(confdir, fn), 'rb').read()
    stem = fn[len('dosbox-x.'):-len('.conf')]  # "base", "1991.ibm_ps2_25_386"
    ident = 'conf_' + stem.replace('.', '_').replace('-', '_')
    chunks.append(carray(ident, data))
    if stem != 'base':
        presets.append((stem.replace('.', '_'), ident))

chunks.append('static const struct { const char *name; const unsigned char *data; size_t len; } dosdrv_conf_presets[] = {')
for name, ident in presets:
    chunks.append(f'\t{{ "{name}", {ident}, sizeof {ident} }},')
chunks.append('};')
chunks.append('#define dosdrv_conf_base conf_base')
chunks.append('#define dosdrv_conf_base_len (sizeof conf_base)')
chunks.append('')

# the disk heads: name -> (zst bytes, full image size). The enum sizes are the
# BizHawk HardDiskOptions values; the zst holds only the nonzero head and the
# memory file's grow supplies the zero tail.
SIZES = {'21mb': 21411840, '41mb': 42823680, '241mb': 252370944,
         '504mb': 527966208, '2014mb': 2111864832}
disks = []
for fn in sorted(os.listdir(hdddir)):
    if not fn.endswith('.img.zst'):
        continue
    key = fn.split('.fat16.')[1][:-len('.img.zst')]
    data = open(os.path.join(hdddir, fn), 'rb').read()
    ident = 'hdd_' + key
    chunks.append(carray(ident, data))
    disks.append((key, ident, SIZES[key]))

chunks.append('static const struct { const char *name; const unsigned char *zst; size_t zstLen; unsigned long long imageSize; } dosdrv_formatted_disks[] = {')
for key, ident, size in disks:
    chunks.append(f'\t{{ "{key}", {ident}, sizeof {ident}, {size}ULL }},')
chunks.append('};')
chunks.append('')

open(out, 'w').write('\n'.join(chunks))
print(f'{out}: {len(presets)} presets, {len(disks)} disks')
