#!/bin/sh
# Configures the GUEST (core.wbx) build: generates a meson cross file for
# miniBox's musl/libstdc++ guest toolchain and sets up build/meson-guest.
#
# Prereq: a miniBox checkout built WITH the C++ guest toolchain:
#   meson setup <miniBox>/build/meson-cpp -Dguest_cpp=true && ninja -C <miniBox>/build/meson-cpp
#
# Usage: ./waterbox/setup-guest.sh [-m <miniBox dir>]
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/.." && pwd)"
mb="${MINIBOX_DIR:-$HOME/chimera/extern/miniBox}"
while getopts "m:" opt; do
	case "$opt" in
		m) mb="$OPTARG" ;;
		*) exit 2 ;;
	esac
done
mb="$(cd "$mb" && pwd)"
mbuild="$mb/build/meson-cpp"
sr="$mbuild/guest-sysroot"
gccver="$(gcc -dumpfullversion)"

[ -f "$sr/lib/libstdc++.a" ] || {
	echo "miniBox C++ guest toolchain missing at $sr." >&2
	echo "Run: meson setup $mbuild $mb -Dguest_cpp=true && ninja -C $mbuild" >&2
	exit 1
}

mkdir -p "$root/build"
cross="$root/build/guest-cross.ini"

# The waterbox code-model flags + the musl specs; every compile and link of
# the guest gets these. C++ adds the guest libstdc++ headers and exceptions
# (DOSBox throws for machine control flow; the unwinder comes from miniBox's
# cxxglue at link).
cat > "$cross" <<EOF
# generated by waterbox/setup-guest.sh - machine-local paths, do not commit
[binaries]
c = 'gcc'
cpp = 'g++'
ar = 'ar'
strip = 'strip'

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
needs_exe_wrapper = true
minibox_dir = '$mb'
minibox_build = '$mbuild'
guest_sysroot = '$sr'

[built-in options]
c_args = ['-specs', '$sr/lib/musl-gcc.specs', '-fvisibility=hidden', '-mcmodel=large', '-mstack-protector-guard=global', '-fno-pic', '-fno-pie', '-fcf-protection=none', '-DCHIMERA_GUEST', '-I$mb/extern/emulibc', '-I$mb/source/guest/include']
cpp_args = ['-specs', '$sr/lib/musl-gcc.specs', '-fvisibility=hidden', '-mcmodel=large', '-mstack-protector-guard=global', '-fno-pic', '-fno-pie', '-fcf-protection=none', '-fexceptions', '-DCHIMERA_GUEST', '-I$mb/extern/emulibc', '-I$mb/source/guest/include', '-I$sr/include/c++/$gccver', '-I$sr/include/c++/$gccver/x86_64-linux-musl']
c_link_args = ['-specs', '$sr/lib/musl-gcc.specs']
cpp_link_args = ['-specs', '$sr/lib/musl-gcc.specs']
EOF

meson setup "$root/build/meson-guest" "$root" --cross-file "$cross" "$@" 2>/dev/null \
	|| meson setup --reconfigure "$root/build/meson-guest" "$root" --cross-file "$cross"
echo "guest build configured: ninja -C build/meson-guest"
