// The chimera guest ABI layer: wraps dosbox-driver into the miniBox core ABI.
// Compiled ONLY for the guest; run-native.cpp is the native twin.
//
// Input: DOSBox's keyboard alone is 101 keys, far past the packed u64, so
// buttons arrive through the engine's wide-input channel - the SetButton
// export, index order EXACTLY waterbox.config's buttons array (generated by
// gen-config.py: 0..99 are KBD_KEYS 1..100, then joysticks, mouse buttons,
// disk-swap controls). run-wbx drives the same exports the frontend does.
#include <cctype>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>

#include <emulibc.h>
#include <waterbox_settings.h>

#include "dosbox-driver.h"
#include "waterbox-input.h"

static char g_loadError[512];
static bool g_inited;
static WbxInput g_input;

// button-index blocks, matching gen-config.py's order
static constexpr int BTN_KEYS = 0;        // 100 keyboard keys (KBD 1..100)
static constexpr int BTN_JOY1 = 100;      // up down left right b1 b2
static constexpr int BTN_JOY2 = 106;
static constexpr int BTN_MOUSE = 112;     // left middle right (LEVELS)
static constexpr int BTN_SWAP = 115;      // prevFD nextFD swapFD prevCD nextCD swapCD
static constexpr int BTN_COUNT = 121;
static uint8_t g_buttons[BTN_COUNT];      // current levels, set by SetButton
static uint8_t g_prevButtons[BTN_COUNT];  // last frame's levels (edges)

// disk-swap selection (guest state: savestates and movies carry it)
static int32_t g_pendingFloppy;
static int32_t g_pendingCD;

static float g_mouseSensitivity = 1.0f;

// ---- video: the live size, clamped to the config's buffer capacity --------

static constexpr int VID_MAX_W = 1024, VID_MAX_H = 768;
static uint32_t g_videoOut[VID_MAX_W * VID_MAX_H];
static int g_vidW = 720, g_vidH = 400; // the text mode every machine boots in
static bool g_videoValid = false;      // no frame rendered yet

static void refreshVideo(void)
{
	int w = 0, h = 0;
	const uint32_t *src = dosdrv_video(&w, &h);
	if (src == nullptr || w <= 0 || h <= 0) return;
	if (w > VID_MAX_W) w = VID_MAX_W;
	if (h > VID_MAX_H) h = VID_MAX_H;
	g_vidW = w;
	g_vidH = h;
	memcpy(g_videoOut, src, (size_t)w * h * sizeof(uint32_t));
	g_videoValid = true;
}

extern "C" {

ECL_EXPORT const char *GetLoadError(void) { return g_loadError; }

ECL_EXPORT int Init(void)
{
	g_loadError[0] = '\0';
	g_input.insertFloppyDisk = -1;
	g_input.insertCDROM = -1;

	// ---- the loaded file: mounted as "rom" -------------------------------
	// The extension comes from "rom.name" when a host mounted it (the test
	// runners do); the frontend mounts only the bytes, so without a name the
	// file is SNIFFED: text is extra configuration, anything up to the
	// largest floppy is a floppy, bigger is a hard disk. Mounted files may
	// be reopened after close (one open at a TIME is the contract), so the
	// probe read here does not spend the imgmount's open.
	std::string romExt;
	bool haveRom = false;
	{
		char romName[256] = "";
		if (FILE *f = fopen("rom.name", "rb")) {
			size_t n = fread(romName, 1, sizeof romName - 1, f);
			while (n > 0 && (romName[n - 1] == '\n' || romName[n - 1] == '\r')) n--;
			romName[n] = '\0';
			fclose(f);
			if (const char *dot = strrchr(romName, '.')) {
				romExt = dot;
				for (char &c : romExt) c = (char)tolower((unsigned char)c);
			}
			haveRom = romName[0] != '\0';
		} else if (FILE *f2 = fopen("rom", "rb")) {
			uint8_t head[512];
			size_t n = fread(head, 1, sizeof head, f2);
			uint8_t pvd[6] = { 0 };
			fseek(f2, 0x8001, SEEK_SET);
			size_t pn = fread(pvd, 1, 5, f2);
			fseek(f2, 0, SEEK_END);
			long size = ftell(f2);
			fclose(f2);
			haveRom = n > 0;
			if (haveRom) {
				bool text = true;
				for (size_t i = 0; i < n && i < 128; i++) {
					if (head[i] != '\t' && head[i] != '\n' && head[i] != '\r'
						&& (head[i] < 0x20 || head[i] > 0x7E)) { text = false; break; }
				}
				if (text) romExt = ".conf";
				else if (pn == 5 && memcmp(pvd, "CD001", 5) == 0) romExt = ".iso";
				else if (size <= 2949120) romExt = ".img"; // up to a 2.88MB floppy
				else romExt = ".hdd";
			}
		}
	}

	// ---- settings (the frontend's channel; defaults match waterbox.config) --
	char preset[128] = "1991_ibm_ps2_25_386";
	wbx_setting_str("machinePreset", preset, sizeof preset);
	char formatted[32] = "none";
	wbx_setting_str("formattedHardDisk", formatted, sizeof formatted);
	int memsizeMB = (int)wbx_setting_double("memsizeMB", -1);
	int cpuCycles = (int)wbx_setting_double("cpuCycles", -1);
	bool joysticks = wbx_setting_bool("joysticksEnabled", 0) != 0;
	g_mouseSensitivity = (float)(wbx_setting_double("mouseSensitivity", 100) / 100.0);

	DosDrvConfig cfg;
	cfg.joystick1Enabled = joysticks;
	cfg.joystick2Enabled = joysticks;

	DosDrvMachine m;
	m.machinePreset = preset;
	m.joysticks = joysticks;
	m.memsizeMB = memsizeMB;
	m.cpuCycles = cpuCycles;

	// ---- what the loaded file IS ------------------------------------------
	if (haveRom && romExt == ".hdd") {
		// the file itself is the writable hard disk's seed
		uint64_t size = 0;
		if (FILE *f = fopen("rom", "rb")) {
			fseek(f, 0, SEEK_END);
			size = (uint64_t)ftell(f);
			fclose(f);
		} else {
			snprintf(g_loadError, sizeof g_loadError, "the rom mount is not readable");
			return 0;
		}
		cfg.hddSeedFile = "rom";
		cfg.writableHDDImageSize = (size + 511) / 512 * 512;
		m.hddMounted = true;
	} else if (haveRom && romExt == ".conf") {
		// extra configuration, appended after everything the settings chose
		if (FILE *f = fopen("rom", "rb")) {
			char chunk[4096];
			size_t n;
			while ((n = fread(chunk, 1, sizeof chunk, f)) > 0) m.extraConf.append(chunk, n);
			fclose(f);
		}
	} else if (haveRom) {
		m.romExt = romExt; // a floppy or disc image: composed into imgmount
	}

	// a formatted disk from settings, when the file itself is not one
	if (!m.hddMounted && strcmp(formatted, "none") != 0) {
		const uint8_t *zst = nullptr;
		size_t zstLen = 0;
		uint64_t size = dosdrv_formatted_disk(formatted, &zst, &zstLen);
		if (size == 0) {
			snprintf(g_loadError, sizeof g_loadError, "unknown formatted disk '%s'", formatted);
			return 0;
		}
		cfg.hddSeedZst = zst;
		cfg.hddSeedZstLen = zstLen;
		cfg.writableHDDImageSize = size;
		m.hddMounted = true;
	}

	cfg.confText = dosdrv_compose_conf(m);

	std::string err;
	if (!dosdrv_boot(cfg, &err)) {
		snprintf(g_loadError, sizeof g_loadError, "%s", err.c_str());
		printf("chimera-dosbox-x: cannot boot: %s\n", err.c_str());
		return 0;
	}
	g_inited = true;
	return 1;
}

// ---- input: the wide channel ----------------------------------------------

ECL_EXPORT void SetButton(int32_t index, int32_t state)
{
	if (index >= 0 && index < BTN_COUNT) g_buttons[index] = state != 0 ? 1 : 0;
}

ECL_EXPORT void SetAxis(int32_t index, int32_t value)
{
	switch (index) {
		case 0: g_input.mouse.posX = value; break;
		case 1: g_input.mouse.posY = value; break;
		case 2: g_input.mouse.speedX = value; break;
		case 3: g_input.mouse.speedY = value; break;
		default: break;
	}
}

// The host may also fill the block directly (run-wbx keeps digest parity with
// run-native this way); SetButton/SetAxis write over it.
ECL_EXPORT WbxInput *GetInputBuffer(void) { return &g_input; }

ECL_EXPORT void FrameAdvance(uint64_t)
{
	if (!g_inited) return;

	// keyboard block: config index i = KBD value i+1
	for (int i = 0; i < 100 && i + 1 < WBX_KEY_COUNT; i++) {
		if (g_buttons[BTN_KEYS + i] != 0) g_input.keys[i + 1] = 1;
		else if (g_prevButtons[BTN_KEYS + i] != 0) g_input.keys[i + 1] = 0;
	}

	auto joy = [](const uint8_t *b, const uint8_t *pb, WbxJoy &o) {
		auto lvl = [&](int k, uint8_t &field) {
			if (b[k] != 0) field = 1;
			else if (pb[k] != 0) field = 0;
		};
		lvl(0, o.up); lvl(1, o.down); lvl(2, o.left); lvl(3, o.right);
		lvl(4, o.button1); lvl(5, o.button2);
	};
	joy(&g_buttons[BTN_JOY1], &g_prevButtons[BTN_JOY1], g_input.joy1);
	joy(&g_buttons[BTN_JOY2], &g_prevButtons[BTN_JOY2], g_input.joy2);

	// mouse buttons: SetButton levels become the block's edge events
	const int L = BTN_MOUSE, M = BTN_MOUSE + 1, R = BTN_MOUSE + 2;
	if (g_buttons[L] && !g_prevButtons[L]) g_input.mouse.leftPressed = 1;
	if (!g_buttons[L] && g_prevButtons[L]) g_input.mouse.leftReleased = 1;
	if (g_buttons[M] && !g_prevButtons[M]) g_input.mouse.middlePressed = 1;
	if (!g_buttons[M] && g_prevButtons[M]) g_input.mouse.middleReleased = 1;
	if (g_buttons[R] && !g_prevButtons[R]) g_input.mouse.rightPressed = 1;
	if (!g_buttons[R] && g_prevButtons[R]) g_input.mouse.rightReleased = 1;
	if (g_input.mouse.sensitivity == 0.0f) g_input.mouse.sensitivity = g_mouseSensitivity;

	// disk-swap controls, edge triggered; the pending index is guest state
	auto rose = [&](int i) { return g_buttons[i] && !g_prevButtons[i]; };
	if (rose(BTN_SWAP + 0)) g_pendingFloppy--;
	if (rose(BTN_SWAP + 1)) g_pendingFloppy++;
	if (rose(BTN_SWAP + 2)) g_input.insertFloppyDisk = g_pendingFloppy < 0 ? 0 : g_pendingFloppy;
	if (rose(BTN_SWAP + 3)) g_pendingCD--;
	if (rose(BTN_SWAP + 4)) g_pendingCD++;
	if (rose(BTN_SWAP + 5)) g_input.insertCDROM = g_pendingCD < 0 ? 0 : g_pendingCD;

	memcpy(g_prevButtons, g_buttons, sizeof g_prevButtons);

	DosDrvInput in;
	memcpy(in.keys, g_input.keys, WBX_KEY_COUNT);
	auto joyOut = [](const WbxJoy &j, DosDrvJoystick &o) {
		o.up = j.up != 0; o.down = j.down != 0; o.left = j.left != 0; o.right = j.right != 0;
		o.button1 = j.button1 != 0; o.button2 = j.button2 != 0;
	};
	joyOut(g_input.joy1, in.joy1);
	joyOut(g_input.joy2, in.joy2);
	in.mouse.posX = g_input.mouse.posX;
	in.mouse.posY = g_input.mouse.posY;
	in.mouse.speedX = g_input.mouse.speedX;
	in.mouse.speedY = g_input.mouse.speedY;
	in.mouse.leftPressed = g_input.mouse.leftPressed != 0;
	in.mouse.middlePressed = g_input.mouse.middlePressed != 0;
	in.mouse.rightPressed = g_input.mouse.rightPressed != 0;
	in.mouse.leftReleased = g_input.mouse.leftReleased != 0;
	in.mouse.middleReleased = g_input.mouse.middleReleased != 0;
	in.mouse.rightReleased = g_input.mouse.rightReleased != 0;
	in.mouse.sensitivity = g_input.mouse.sensitivity != 0.0f ? g_input.mouse.sensitivity : 1.0f;
	in.insertFloppyDisk = g_input.insertFloppyDisk;
	in.insertCDROM = g_input.insertCDROM;
	if (g_input.framerateNumerator > 0 && g_input.framerateDenominator > 0) {
		in.framerateNumerator = g_input.framerateNumerator;
		in.framerateDenominator = g_input.framerateDenominator;
	} else {
		int rn = 0, rd = 0;
		dosdrv_refresh_rate(&rn, &rd);
		if (rn > 0 && rd > 0) {
			in.framerateNumerator = rn;
			in.framerateDenominator = rd;
		}
	}

	// one-shot fields: consumed by this frame
	g_input.insertFloppyDisk = -1;
	g_input.insertCDROM = -1;
	g_input.mouse.leftPressed = g_input.mouse.middlePressed = g_input.mouse.rightPressed = 0;
	g_input.mouse.leftReleased = g_input.mouse.middleReleased = g_input.mouse.rightReleased = 0;

	dosdrv_frame(in);
	refreshVideo();
}

// null until the first rendered frame - the reference runner skips unrendered
// frames in its digest and the sandbox must look identical
ECL_EXPORT uint32_t *GetVideoBgra(void) { return g_videoValid ? g_videoOut : nullptr; }
ECL_EXPORT int GetVideoWidth(void) { return g_vidW; }
ECL_EXPORT int GetVideoHeight(void) { return g_vidH; }

ECL_EXPORT int16_t *GetAudio(void)
{
	int n = 0;
	return const_cast<int16_t *>(dosdrv_audio(&n));
}
ECL_EXPORT int GetAudioSampleCount(void)
{
	int n = 0;
	dosdrv_audio(&n);
	return n > 4096 ? 4096 : n; // the config's buffer capacity
}

// The DOS video mode's own refresh rate when the VGA emulation has reported
// one, else the classic 70.086 Hz text mode (3146888/44900).
ECL_EXPORT int GetVsyncNumerator(void)
{
	int n = 0, d = 0;
	dosdrv_refresh_rate(&n, &d);
	return n > 0 && d > 0 ? n : 3146888;
}
ECL_EXPORT int GetVsyncDenominator(void)
{
	int n = 0, d = 0;
	dosdrv_refresh_rate(&n, &d);
	return n > 0 && d > 0 ? d : 44900;
}

ECL_EXPORT uint32_t GetTicksElapsed(void) { return dosdrv_ticks_elapsed(); }
ECL_EXPORT int GetDriveActivityFlag(void) { return dosdrv_drive_activity() ? 1 : 0; }

// ---- memory domains ----

ECL_EXPORT int GetMemoryDomainCount(void)
{
	int n = 0;
	while (dosdrv_domain(n, nullptr, nullptr, nullptr, nullptr)) n++;
	return n;
}
ECL_EXPORT const char *GetMemoryDomainName(int i)
{
	const char *name = nullptr;
	dosdrv_domain(i, &name, nullptr, nullptr, nullptr);
	return name;
}
ECL_EXPORT uint8_t *GetMemoryDomainPtr(int i)
{
	uint8_t *data = nullptr;
	dosdrv_domain(i, nullptr, &data, nullptr, nullptr);
	return data;
}
ECL_EXPORT int64_t GetMemoryDomainSize(int i)
{
	uint64_t size = 0;
	dosdrv_domain(i, nullptr, nullptr, &size, nullptr);
	return (int64_t)size;
}
ECL_EXPORT int GetMemoryDomainWritable(int i)
{
	bool w = false;
	return dosdrv_domain(i, nullptr, nullptr, nullptr, &w) && w ? 1 : 0;
}

// ---- savedata export (the sixth optional guest ABI group) ----
// The writable hard disk image is this core's save data (chimera
// docs/save-data.md): it lives in guest memory (the sealed baseline carries
// the seed; savestates only the dirtied pages), and this group is the user's
// way OUT - one file, the whole image.

ECL_EXPORT int32_t GetSaveDataFileCount(void) { return dosdrv_hdd_size() != 0 ? 1 : 0; }
ECL_EXPORT const char *GetSaveDataFileName(int32_t i) { return i == 0 ? "HardDiskDrive.img" : nullptr; }
ECL_EXPORT int64_t GetSaveDataFileSize(int32_t i) { return i == 0 ? (int64_t)dosdrv_hdd_size() : 0; }
ECL_EXPORT const uint8_t *GetSaveDataFileBuffer(int32_t i) { return i == 0 ? dosdrv_hdd_buffer() : nullptr; }

}  // extern "C"
